batch_size: 32 # Int
epochs: 5 # Int
learning_rate: 0.001 # Float
num_classes: 1 # Int
window_size: 100
weighted_loss: False # Boolean
val_size: 0.2 # Float: Size of validation in train/val split
shuffle_split: True # Boolean: whether to shuffle samples. NOT FOR TIMESERIES
model_type: 'resnet'
normalize:
  run: True # Boolean: bypasses method
  method: standard # String: minmax, standard, or mean