batch_size: 32 # Int
epochs: 5 # Int
learning_rate: 0.001 # Float
num_classes: 1 # Int
window_size: 60
weighted_loss: False # Boolean
loss: mse
training_amount: 10
validation_amount: 8

shuffle_split: True # Boolean: whether to shuffle samples. NOT FOR TIMESERIES
normalize:
  run: True # Boolean: bypasses method
  method: standard # String: minmax, standard, or mean
